### ISSUE TITLE
ion-sfu/pkg/log moved

### ISSUE THREAD

**Issue by tomsun** [pion/ion-examples#37]
https://github.com/pion/ion-examples/blob/3d4f1328704a50d3269a8d634c25bb3e16aff501/ion-sfu/custom-signaling/main.go#L21

> module github.com/pion/ion-sfu@latest found (v1.0.34), but does not contain package github.com/pion/ion-sfu/pkg/log

see also: https://github.com/pion/ion-sfu/commit/c204ceabedeb8a3473ecc14133402ff8cb73f6dc

**Comment by TannerGabriel** [comment]
You are right. The package has moved to [pion/ion-log](https://github.com/pion/ion-log). I will update the example and fix this.
